authors:
  rc-sea:
    name: RC Carter
    description: Founder, Exupérian. Longtime product person.
    avatar: https://avatars.githubusercontent.com/u/12474675?v=4
    url: https://github.com/rc-sea
